### ISSUE TITLE
report server undefined

### ISSUE THREAD

**Issue by ShockAnWave** [iamvikshan/amina#254]
![Screenshot 2024-11-02 233250](https://github.com/user-attachments/assets/765c8f29-bf4d-46b7-b986-2b467fdfe071)

**Comment by ShockAnWave** [comment]
@iamvikshan

**Comment by iamvikshan** [comment]
thank you, i will look into it @ShockAnWave

**Comment by iamvikshan** [comment]
Ah, you are trying to report a server that the bot is not in, to avoid abuse, you cannot report a server the bot is not in, otherwise the bot cannot resolve it. please lmk if really the bot is in that server. paste the server id in the `/report > feedback` if you do not want to expose the id, i will see it and validate. all said, i need to add better response for when the server does not exist

**Comment by iamvikshan** [comment]
I thought about it, and due to security and privacy restrictions imposed by Discord's API. Bots can only access data within the servers they have been added to and have the necessary permissions for, but I can get away with that, still respecting privacy. This would require the dashboard however, as the bot can fetch server info of servers YOU are in. The bot will flag the server and create an invite as you. This allows the developers to inspect servers by joining them. The developers can then blacklist a server if they think it is harmful. 

This is just a possible way to do it, but as I said, it is a thought. I might add it if needed

PS: all reports (including the current report system) include server invites created by the bot. I don't think it is a privacy concern as when being added, the bot will ask for invite perms.
